rmqtt-bin/gen_x509.sh, rmqtt-bin/src/server.rs, rmqtt.toml, rmqtt/src/settings/listener.rs
* 在tls配置cross_cert 为true的时候支持x509证书双向认证
* gen_x509.sh脚本可以用于生成示例证书
使用脚本前需要配置脚本内的DNS和IP参数，授信客户端连接Broker的服务域名或IP。
=> add x509 cross cert

rmqtt-plugins/rmqtt-auth-http/Cargo.toml, rmqtt-plugins/rmqtt-auth-http/src/lib.rs
- Bump version from 0.1.2 to 0.1.3
- Remove global HTTP_CLIENT singleton using once_cell
- Add instance-based reqwest::Client as plugin member
- Pass HTTP client through to AuthHandler
- Replace static client initialization with new_reqwest_client() function
- Update all HTTP request methods to use instance client
- Remove once_cell dependency
- Improve request handling with instance-specific client
=> refactor(auth-http): remove global HTTP client and bump version to 0.1.3

README-CN.md, README.md
- Added DeepWiki badge to both English and Chinese READMEs
- Badge links to RMQTT documentation on DeepWiki
- Helps users quickly access AI-powered documentation
=> docs: add DeepWiki support badge to READMEs

Cargo.toml
- Bump version from 0.15.0-rc.2 to 0.15.0-rc.3
- Update workspace package version
- Update rmqtt dependency version to match
=> chore(release): prepare for v0.15.0-rc.3 release

rmqtt/src/context.rs, rmqtt/src/grpc.rs, rmqtt/src/stats.rs
- Split single global task executor into two separate executors:
* server_exec: Handles server-side tasks (gRPC, etc)
* client_exec: Handles client-related tasks
- Update all references to use the appropriate executor:
* gRPC server uses server_exec
* Client operations use client_exec
- Enhance stats tracking:
* Separate debug_server_exec_stats and debug_client_exec_stats
* Update stats collection methods
- Improve documentation:
* Clarify executor purposes in comments
* Update stats module docs
- Benefits:
* Better task isolation
* More granular performance tracking
* Reduced contention between server/client operations
* Improved system stability under load
- Maintains backward compatibility with existing metrics
=> refactor(task-exec): split global executor into server/client executors

rmqtt-plugins/rmqtt-cluster-raft/Cargo.toml, rmqtt-plugins/rmqtt-cluster-raft/src/shared.rs
- Bump version from 0.1.6 to 0.2.0 (minor version bump for backward-compatible changes)
- Update task executor usage to use client_exec instead of global_exec:
* Forwards future now runs on client task executor
* Better aligns with new task execution separation strategy
- Changes maintain all existing functionality while:
* Improving task isolation
* Better matching task types with appropriate executors
* Following the new server/client executor pattern
=> feat(cluster-raft): bump version to 0.2.0 and update task executor usage

rmqtt/src/types.rs
- Replace direct `running` field access with `is_running()` method call
- Maintain same JSON serialization behavior
=> fix(types): use is_running() method instead of direct field access

rmqtt-plugins/rmqtt-cluster-raft/Cargo.toml
- Update rmqtt-raft version from 0.5.2 to 0.5.3
- Maintain all existing features ("reuse" feature still enabled)
- Keep commented local path reference for development purposes
=> chore(cluster-raft): update rmqtt-raft dependency to 0.5.3

Cargo.toml, rmqtt-plugins/rmqtt-cluster-raft/Cargo.toml, rmqtt/src/broker/v3.rs, rmqtt/src/broker/v5.rs
Core Changes:
- Bump workspace version from 0.13.1 to 0.13.2
- Add handshake timeout checks for both MQTT v3 and v5 protocols
- Track handshake start time and enforce listener.handshake_timeout
- Return ServiceUnavailable/ServerUnavailable when timeout exceeded
Dependency Updates:
- Update rmqtt-raft dependency from 0.4.5 to 0.5.3
- Maintain reuse feature flag for raft implementation
Protocol Improvements:
- v3: Added timeout check before client ID validation
- v5: Added timeout check before client ID validation
- Both protocols now properly handle handshake timeouts
=> feat(handshake): add timeout checks and update dependencies

Cargo.toml
- Set `panic = "abort"` in release profile configuration
- Improves release binary size by removing panic unwinding infrastructure
- Maintains existing optimization settings (lto=true, opt-level='s')
=> build: enable panic abort in release profile

Cargo.toml, rmqtt-plugins/rmqtt-acl/Cargo.toml, rmqtt-plugins/rmqtt-auth-http/Cargo.toml, rmqtt-plugins/rmqtt-auto-subscription/Cargo.toml, rmqtt-plugins/rmqtt-bridge-egress-kafka/Cargo.toml, rmqtt-plugins/rmqtt-bridge-egress-nats/Cargo.toml, rmqtt-plugins/rmqtt-bridge-ingress-kafka/Cargo.toml, rmqtt-plugins/rmqtt-cluster-broadcast/Cargo.toml, rmqtt-plugins/rmqtt-counter/Cargo.toml, rmqtt-plugins/rmqtt-http-api/Cargo.toml, rmqtt-plugins/rmqtt-retainer/Cargo.toml, rmqtt-plugins/rmqtt-sys-topic/Cargo.toml, rmqtt-plugins/rmqtt-topic-rewrite/Cargo.toml, rmqtt/src/types.rs
This commit prepares the v0.15.0-rc.7 release with version increments across multiple components:
- ACL bumped to 0.1.2
- Auto-subscription bumped to 0.1.1  
- Kafka bridge bumped to 0.1.1
- NATS bridge bumped to 0.1.1
- HTTP API incremented to 0.2.1
- Topic rewrite bumped to 0.1.1
- Auth HTTP bumped to 0.1.4
- Kafka ingress bumped to 0.1.2
- Retainer bumped to 0.1.2
- System topic bumped to 0.1.2
- Cluster broadcast bumped to 0.1.4
- Counter bumped to 0.1.1
- Core version bumped to 0.15.0-rc.7 with bitflags import update
All version updates were performed in preparation for the upcoming release candidate.
=> chore(release): prepare v0.15.0-rc.7 release with multiple component version bumps

Cargo.toml, rmqtt-plugins/rmqtt-bridge-egress-kafka/src/bridge.rs, rmqtt-plugins/rmqtt-bridge-egress-mqtt/src/bridge.rs, rmqtt-plugins/rmqtt-bridge-egress-nats/src/bridge.rs, rmqtt-plugins/rmqtt-bridge-egress-pulsar/src/bridge.rs, rmqtt-plugins/rmqtt-bridge-egress-reductstore/src/bridge.rs, rmqtt-plugins/rmqtt-bridge-ingress-pulsar/src/config.rs, rmqtt-plugins/rmqtt-http-api/src/types.rs, rmqtt-plugins/rmqtt-session-storage/src/session.rs, rmqtt/src/broker/session.rs, rmqtt/src/broker/types.rs, rmqtt/src/plugin.rs
Version & Core:
- Bumped workspace version from 0.13.3 to 0.13.4
Performance Improvements:
- Changed offline_messages from Vec to VecDeque for efficient FIFO operations
- Replaced pop() with pop_front() for proper queue behavior
- Used push_back() instead of push() for correct queue ordering
Key Benefits:
1. **Efficiency**: VecDeque provides O(1) amortized time for both ends
2. **Correctness**: Ensures proper first-in-first-out delivery of offline messages
3. **Memory**: Better memory utilization for queue operations
4. **Behavior**: Maintains message ordering during offline storage and retrieval
The changes ensure that offline messages are processed in the correct order while improving performance for queue operations.
=> perf(session): optimize offline message handling with VecDeque

README-CN.md, README.md
Documentation Enhancements:
1. **Added Crate Badges**:
- Added crates.io version badge for visibility
- Added docs.rs documentation badge pointing to latest version
- Added to both English and Chinese READMEs
2. **Library Mode Documentation**:
- Added new "Library Mode Integration" section in both languages
- Provides clear instructions for embedding rmqtt as a Rust dependency
- Includes example Cargo.toml dependency configuration
- Links to detailed library documentation in rmqtt/README.md
3. **Bilingual Support**:
- English version: "Library Mode Integration"
- Chinese version: "通过库方式集成" (Library Mode Integration)
- Consistent structure and information across both languages
Benefits:
- **Better Discoverability**: Developers can easily find the crate on crates.io
- **Improved …
=> docs: add library mode integration and crate badges to README

Cargo.toml, rmqtt/README.md, rmqtt/examples/plugin/Cargo.toml, rmqtt/examples/plugin/src/main.rs, rmqtt/examples/plugins/Cargo.toml, rmqtt/examples/plugins/src/main.rs
Release Preparation:
- Bumped version from 0.15.0-rc.7 to 0.15.0 (stable release)
- Updated workspace dependencies to use 0.15.0
Documentation Enhancements:
1. **Version Updates**: Changed all version references from 0.15.0-rc to 0.15.0
2. **Enhanced Plugin Examples**: Added comprehensive plugin usage examples:
- Basic plugin registration with rmqtt-plugins meta-package
- Programmatic configuration with plugins_config_map_add()
- Individual plugin dependency approach
3. **New Examples**: Added two new plugin configuration patterns:
- Using rmqtt-plugins with "full" feature
- Programmatic ACL rule configuration
4. **Example Improvements**:
- Simplified logging in plugin example (env_logger → simple_logger)
- Cleaned up main.rs with better commenting
- Updated Cargo.toml dependencies
5. …
=> chore: release version 0.15.0 and update documentation

.gitignore
- Added `/publishs-dry-run.bat` to gitignore
- Added `/publishs.bat` to gitignore
These files are likely local/automated publish scripts that should not be tracked in version control.
=> chore(gitignore): add publish script files to gitignore

rmqtt-bin/src/server.rs
- Reduced shutdown delay from 1 second to 100 milliseconds
- Added explicit `std::process::exit(0)` for immediate termination
- Maintains cleanup opportunity while improving shutdown responsiveness
This change provides faster service termination while ensuring the process exits cleanly.
=> perf(shutdown): reduce shutdown delay and exit explicitly

rmqtt-plugins/rmqtt-cluster-broadcast/src/shared.rs, rmqtt-plugins/rmqtt-cluster-raft/src/router.rs, rmqtt-plugins/rmqtt-cluster-raft/src/shared.rs, rmqtt/src/shared.rs
Refactored the shared module across cluster implementations to support two distinct forwarding modes:
1. **Targeted Client Forwarding** (`forward_to_target_client`):
- New method added to directly forward messages to a specific client ID
- Handles both local and cross-node forwarding scenarios
- Uses gRPC for inter-node communication with timeout handling
- Maintains statistics for forwarding operations
2. **Subscription-Based Forwarding** (`forward_to_subscriptions`):
- Existing broadcast logic now encapsulated in this method
- Maintains previous behavior for non-targeted messages
**Key Changes:**
* Added `get_target_node_id()` method to router for client-node mapping
* Modified main `forwards()` method to dispatch based on `publish.target_clientid` presence
* Implemented consistent …
=> feat(shared): add targeted client forwarding support

rmqtt-net/Cargo.toml
Updated the version of rmqtt-net crate to 0.2.0 to reflect API changes and new functionality.
=> chore(net): bump version from 0.1.5 to 0.2.0

Cargo.toml
Updated the rmqtt-net workspace dependency from 0.1 to 0.2 to match the recent version bump.
=> chore(deps): update rmqtt-net dependency to 0.2.0

README-CN.md, README.md, docs/en_US/mqtt-protocol.md, docs/zh_CN/mqtt-protocol.md
* Add documentation links for MQTT protocol support in both Chinese and English README
* Add specific anchor links for QoS levels explanation in protocol documentation
* Maintain consistent formatting with previous documentation improvements
=> docs: add detailed documentation links for MQTT protocol features
